---
- name: Ensure PIP is installed.
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python-pip

- shell: ls /usr/local/lib/python2.7/dist-packages/requests*
  register: directory_to_clean
  ignore_errors: yes

- file:
    name: "{{item}}"
    state: absent
    recurse: yes
    with_items: directory_to_clean.stdout_lines
