---
- name: Ensure PIP is installed.
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python-pip

- shell: ls /usr/local/lib/python2.7/dist-packages/ | grep requests*
  register: directory_to_clean
  ignore_errors: yes

- debug:
    msg: "Directories : {{ item }}"
  with_items: directory_to_clean.stdout_lines
  when: directory_to_clean.stdout_lines is defined

- file:
    name: "{{item}}"
    state: absent
  with_items: directory_to_clean.stdout_lines
